In [75]:
import duckdb 
import pandas as pd

# Exploration of admissions data

In [25]:
# Create a duckdb session/connection
admissions_con: duckdb.DuckDBPyConnection = duckdb.connect()

# Read SQL file
with open("sql_files/admissions.sql", "r") as f:
    sql: str = f.read()

admissions_result: pd.DataFrame = admissions_con.execute(sql).df() # remember to fetch result using df()
admissions_result

   avg(subject_count)
0            2.443603

# Exploration of diagnoses data

In [76]:
diagnoses_con: duckdb.DuckDBPyConnection = duckdb.connect()

# Read SQL file
with open("sql_files/diagnoses_sql/active_cancer.sql", "r") as f:
    sql: str = f.read()

diagnoses_result: pd.DataFrame = diagnoses_con.execute(sql).df() # remember to fetch result using df()
diagnoses_result

   count(DISTINCT subject_id)
0                       29369

In [103]:
total_diagnoses_patients_con: duckdb.DuckDBPyConnection = duckdb.connect()

diagnoses_sql_queries = ["active_cancer", "personal_history_cancer"]

# Perform SQL queries so multiple files can be loaded. 
for query in diagnoses_sql_queries:
    with open(f"sql_files/diagnoses_sql/{query}.sql", "r") as f:
        sql: str = f.read()
        total_diagnoses_patients_con.execute(sql).df()
        
with open(f"sql_files/diagnoses_sql/history_and_active.sql", "r") as f:
    total_cancer_patients_sql: str = f.read()


total_diagnoses_result: pd.DataFrame = total_diagnoses_patients_con.execute(total_cancer_patients_sql).df()
total_diagnoses_result

       subject_id
0        10470555
1        10471837
2        10486853
3        10511623
4        10512033
...           ...
48433    18816093
48434    18957585
48435    18966771
48436    18983727
48437    19118815

[48438 rows x 1 columns]

# Exploration of prescriptions data

1. Look at how many patients have had antineoplasts or specific drugs across the entire dataset. 
2. Perform 1. but within the total number of cancer patients.

In [105]:
prescriptions_con: duckdb.DuckDBPyConnection = duckdb.connect()

# Read SQL file
with open("sql_files/prescriptions_sql/prescriptions_count.sql", "r") as f:
    sql: str = f.read()

prescriptions_result: pd.DataFrame = prescriptions_con.execute(sql).df() # remember to fetch result using df()
prescriptions_result

      subject_id
0       10001843
1       10083304
2       10108709
3       10131237
4       10191971
...          ...
3217    19915124
3218    19935888
3219    19963038
3220    19982183
3221    19989134

[3222 rows x 1 columns]

# Find intersection of diagnoses and prescriptions

In [113]:
common_diag_prescript_patients: pd.DataFrame = total_diagnoses_result[total_diagnoses_result["subject_id"].isin(prescriptions_result["subject_id"])]
common_diag_prescript_patients

       subject_id
8        10554780
31       10777749
34       10793648
92       15704389
119      11600572
...           ...
48381    13992510
48398    18176556
48399    11134447
48425    11973164
48432    15702558

[3091 rows x 1 columns]

# Find cancer-related procedures

In [114]:
procedures_con: duckdb.DuckDBPyConnection = duckdb.connect()

# Read SQL file
with open("sql_files/procedures_sql/procedures_count.sql", "r") as f:
    sql: str = f.read()

procedures_result: pd.DataFrame = procedures_con.execute(sql).df() # remember to fetch result using df()
procedures_result

      subject_id
0       10002155
1       10003019
2       10035168
3       10064049
4       10098008
...          ...
2886    19930120
2887    19930554
2888    19949164
2889    19956654
2890    19963140

[2891 rows x 1 columns]

# Find intersection of cancer diagnoses and procedures

In [115]:
common_diag_procedure_patients: pd.DataFrame = total_diagnoses_result[total_diagnoses_result["subject_id"].isin(procedures_result["subject_id"])]
common_diag_procedure_patients

       subject_id
8        10554780
13       10566950
20       10666715
34       10793648
45       10859137
...           ...
48196    18529025
48220    19034797
48253    17332316
48399    11134447
48425    11973164

[2809 rows x 1 columns]